import{StyleSheet} from 'react-native'
import Color from '../../../../src/shared/theme/Colors'


const styles = StyleSheet.create({
  container: { padding: 16, backgroundColor: Color.card },
  locationContainer:{flexDirection:'row', marginLeft:-8},
  block: { paddingVertical: 10 },
  row: { flexDirection: 'row', alignItems: 'center' },
  separator: { height: 1, backgroundColor: Color.separator },
  boldText: { fontSize: 11, fontWeight: '600', color: Color.bold },
  subText: { fontSize: 13, color: Color.sub, marginTop: 2 },
  totalText: { fontSize: 16, fontWeight: '700', color: Color.total },
  tipRow: { flexDirection: 'row', marginTop: 10 },
  tipButton: { borderWidth: 1, paddingHorizontal: 14, paddingVertical: 6, marginRight: 8, },
  tipButtonSelected: { backgroundColor: Color.borderColor, borderColor: Color.borderColor },
  tipText: { color: Color.tip, fontSize: 13 },
  tipTextSelected: { color: Color.card, fontSize: 13, fontWeight: '600' },
  checkbox: { width: 18, height: 18, borderRadius: 4, borderWidth: 1, borderColor: Color.border, marginRight: 8, },
  downIcon:{ marginLeft:8 },
  timingContainer:{flexDirection:'row', marginTop:10, marginLeft:-8},
  checkboxChecked: { backgroundColor: Color.checkbox, borderColor: Color.checkbox },
  DeliveryText: { fontSize: 11, fontWeight: '600', color: Color.bold, marginLeft:5 },
  cartText:{ fontSize:16 , marginLeft:10},
  vegIcon:{ resizeMode:'contain', width:14, height:14 ,marginLeft:-4 },
  priceText:{ fontSize:11, marginLeft:12 },
  priceSecondText:{ fontSize:11, textAlign:'right', marginRight:6 },
  counterContainer:{ flexDirection:'row', marginLeft:120, marginTop:15, gap:10, borderWidth:1, width:56, height:22, paddingLeft:4, backgroundColor:Color.counter, justifyContent:'center', },
  counterButton:{ marginTop:-8, fontSize:24, color:Color.counterButton },         
  counterText:{ fontSize:12 },
  addOnText:{ fontSize:10, color:Color.add, marginTop:-6, marginLeft:12 },
  cookingButton:{ alignItems:'center', marginTop:20 },
  cookingButtonText:{ color:Color.cooking , },
  dotedLine:{ borderStyle:'dotted',borderWidth:0.5, paddingHorizontal:110, color:Color.line, marginTop:4},
  OfferText:{ color:Color.resend },
  offerContainer:{ flexDirection:'row' },
  link: {  marginLeft:100 },
  linkText:{fontSize: 13, color: Color.borderColor, fontWeight: '600'},
  labelText:{ marginLeft:5 },
  subLabelText:{fontSize:9, color:Color.add, marginLeft:26},
  subtitleText:{fontSize:12, color:Color.add, marginTop:5, marginLeft:4},
  tipIcon:{},
  buttonRow:{flexDirection:'row', gap:5},
  rowBillLine:{ flexDirection:'row', padding:5, marginLeft:6, justifyContent:'space-between', },
  addButton:{ marginLeft:240, position:'absolute', marginTop:6 },
  addButtonText:{ color:Color.addText },
  billBlock: { paddingVertical: 10, backgroundColor:Color.bill },
  covidText:{ fontSize:14 },
  covidSubText:{ fontSize:12, color:Color.add, marginLeft:26, marginTop:5 },
  deliveryBlock:{ },
  deliveryBlockRow:{flexDirection:'row'},
  voiceButtonText:{ color:Color.counterButton, marginLeft:28 },
  changeButton:{color:Color.counterButton,marginLeft:130},
  deliveryTypeText:{ fontSize:16 },
  handText:{ color:Color.add },
  handRow:{ flexDirection:'row', padding:6, gap:5 },
  detailText:{ fontSize:16 },
  detailRow:{ flexDirection:'row', gap:2 },
  userDetailText:{ fontSize:12, },
  orderText:{ fontSize:16 },
  orderblock:{ gap:70 },
  addlink:{ color:Color.addText },
  climateText:{ fontSize:16 },
  climateRow:{ flexDirection:'row' },
  climateContainer:{ padding:12 },
  climateSubText:{ marginLeft:20, color:'#817070', fontSize:12 },
  knowText:{ color:Color.addText, marginLeft:20 },
  errorText: { fontSize: 12, color: Color.borderColor, marginTop: 10, marginLeft:20 },
  gpayIcon:{ width:35, height:18, resizeMode:'contain' },
  orderButton:{ backgroundColor:Color.primary, width:220, height:61, marginLeft:5, marginTop:-20 },
  buttonPrice:{ color:Color.button, fontSize:20, marginLeft:10, marginTop:10 },
  buttonText:{ color:Color.button, fontSize:20, marginLeft:100 , marginTop: -20},
  buttonSecondText:{ color:Color.button, marginTop:-12, marginLeft:10 },
  rowContainer:{ flexDirection:'row', marginTop:40 },
  payText:{ fontSize:13 },
  payIcon:{marginTop:5},
  gPayText:{marginTop:-20},
  transparentContainer:{ flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end', },
  mainContainer:{height: '80%', backgroundColor: 'white', borderTopLeftRadius: 20, borderTopRightRadius: 20, overflow: 'hidden',},
  closeButton: { marginLeft:160, marginBottom:10, width: 32, height: 32, borderRadius: 16, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', alignItems: 'center', zIndex: 10, },

});export default styles;