import { StyleSheet } from "react-native"
import Color from "../../../shared/theme/Colors";

const styles = StyleSheet.create({
    container:{ flex:1, backgroundColor:Color.button,},
    icon:{ paddingTop:50, marginLeft:10, },
    restaurantRow:{ flexDirection:'row', justifyContent: 'space-between' },
    restaurantInfoContainer:{ marginLeft:20, marginTop:15, marginHorizontal: 20, },
    restaurantNameText:{ fontFamily: 'Signika', fontWeight: 400, fontSize: 26, letterSpacing: 0, },
    restaurantDescription:{ fontFamily: 'Segoe UI', fontWeight: 400, fontSize: 12, letterSpacing: 0, },
    locationText:{ fontFamily: 'Segoe UI', fontWeight: 400, fontSize: 10, letterSpacing: 0, },
    iconContainer:{ marginTop:5, },
    buttonGroup:{ marginTop:12, flexDirection:'row', marginHorizontal:10, width:'95%', backgroundColor:'#F0EBEB', borderRadius:5, height:50 },
    activeDelivery:{ backgroundColor:Color.resend, width:'33%' ,height:50},
    activeDining:{backgroundColor:Color.resend, width:'33%' ,height:50},
    disableDelivery:{},
    activeTextDelivery:{ color:Color.button, fontFamily:'Segoe UI' },
    disableTextDelivery:{ color:Color.cooking , paddingTop:6},
    disableDining:{ width:'31%' ,height:50},
    disableReview:{ width:'31%' },
    modeIcon:{ resizeMode:'contain', width:'94%', marginLeft:12, height:40 },
    deliveryContainer:{ backgroundColor:Color.delivery, width:86, height:42, marginLeft:50, paddingLeft:10, borderRadius:4, },
    starContainer:{ flexDirection:'row', gap:5, marginTop:2 },
    numberText:{ fontFamily: 'Segoe UI', fontWeight: 400, fontSize: 13, letterSpacing: 0, color:Color.button },
    starIcon:{ marginTop:3 },
    deliveryText:{ fontFamily: 'Segoe UI', fontWeight: 400, fontSize: 12, letterSpacing: 0, color:Color.button },
    deliveryIcon:{ resizeMode:'contain', width:86, height:42, marginLeft:50, marginTop:5, borderRadius:4, },
    text:{ backgroundColor: 'rgba(0,0,0,0.5)', fontFamily: 'Segoe UI', fontWeight: 400, fontSize: 12, letterSpacing: 0, color:Color.button, flex: 1, paddingLeft:10, paddingTop:2 },
    maxIcon:{ resizeMode:'contain', marginTop:5, width:47, height:23 },
    bikeContainer:{ backgroundColor:Color.bike, width:'92%', height:30, marginLeft:10, marginTop:20, flexDirection:'row', alignItems:'center', borderRadius:5 },
    bikeIcon:{ paddingLeft:15, },
    bikeIconText:{ paddingLeft:5 },
    menuButtonGroup:{ backgroundColor:Color.menu, flexDirection:'row', marginTop:15, },
    activeHealthy:{ width:'30%'},
    disableHealthy:{ },
    activeTextHealthy:{ color:Color.resend, fontFamily:'Signika' , fontSize:17, marginLeft:24, marginTop:15,},
    disableTextHealthy:{ color:Color.cooking },
    switchContainer:{ flexDirection:'row', gap:40, marginTop:-10 },
    searchFieldContainer:{paddingTop:10},
    searchField:{ height:45, width:110, marginTop:16, borderWidth:1, opacity:0.2, borderRadius:6 },
    searchIcon:{ position:'absolute', marginTop:38, marginLeft:4 },
    searchFieldText:{ textAlign:'center', color:Color.line },
    switchButtonContainer:{ flexDirection:'row', marginTop:10, gap:40 },
    lineContainer:{ width:'100%', borderWidth:1, marginTop:28, opacity:0.25 },
    recomendedContainer:{ flexDirection:'row', gap:240, marginLeft:15, marginTop:25, },
    recomendedText:{ fontFamily: 'Segoe UI', fontWeight: 400, fontSize: 12, letterSpacing: 0, },
    menuCard: { flexDirection: 'row', justifyContent: 'space-between', padding: 12, borderBottomWidth: 1, borderBottomColor: Color.separator, },
    menuInfo: { flex: 1, paddingRight: 10, },
    menuName: { fontSize: 15, fontWeight: 'bold', marginBottom: 4, },
    menuText: { fontSize: 13, color: Color.tip, marginBottom: 4, },
    menuImage: { width: 90, height: 90, borderRadius: 8, },
    addButton: { marginTop: -10, borderWidth: 1, borderColor: 'red', borderRadius: 5, paddingVertical: 4, alignItems: 'center', width:80, marginLeft:5, backgroundColor:Color.addBText, },
    addButtonText: { color: 'red', fontWeight: 'bold', },
    ratingIcon:{ width:80, resizeMode:'contain', marginTop:-12, marginLeft:4 },
    mustText:{ backgroundColor:Color.addBText, width:46, height:17, fontSize:10, textAlign:'center', color:Color.addText, borderRadius:4, marginTop:5 },
    rowContainer:{ flexDirection:'row', gap:10 },
    offIcon:{ width:414, height:51 , marginBottom:2},
    PlaceOrder:{backgroundColor:Color.primary,borderRadius:2 },
    inputRow:{flexDirection:'row',marginTop: -20, borderWidth: 1, borderColor: 'red', borderRadius: 5, paddingVertical: 4, alignItems: 'center', width:80, marginLeft:5, backgroundColor:Color.primary,gap:10},
    inputButtonText:{fontSize:22, marginLeft:10, color:Color.button},
    quantityText:{fontSize:16, marginLeft:5, color:Color.button},
    butContainer:{paddingHorizontal:20, paddingBottom:5, marginBottom:20,},
    buttonContainer:{flexDirection:'row', justifyContent:'space-between', marginBottom:-10},
    quantityButton:{marginLeft:4, color:Color.button, padding:6},
    priceButton:{marginLeft:10, color:Color.button,paddingBottom:6 },
    cartButton:{color:Color.button, padding:10, marginTop:2},
    underline: { height: 2, width: '60%', backgroundColor: Color.underline, marginTop: 9, alignSelf: 'center', }
});
export default styles;